version: "3.8"

services:
  mysql_db1:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword1
      MYSQL_DATABASE: database1
      MYSQL_USER: user1
      MYSQL_PASSWORD: password1
    volumes:
      - mysql_data1:/var/lib/mysql
    ports:
      - "3306:3306"

  mysql_db2:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword2
      MYSQL_DATABASE: database2
      MYSQL_USER: user2
      MYSQL_PASSWORD: password2
    volumes:
      - mysql_data2:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    build: ./backend
    depends_on:
      - mysql_db1
      - mysql_db2
    environment:
      SERVER_ADDRESS: http://127.0.0.1:3005
      SERVER: http://127.0.0.1/
      DATABASE_URL_1: mysql://root:root@mysql:3306/video_generator
      DATABASE_URL_2: mysql://root:root@mysql:3306/olybible
      SERVER_PORT: 3006
    ports:
      - "3006:3006"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3005:3005"
    environment:
      VITE_API_BASE_URL: /
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
